#define PIN_VOL			3		
#define PIN_FX1			4
#define PIN_NEXT_FX		14
#define PIN_BACK_FX		13
#define PIN_TOGGLE_BP	15
#define PIN_LED_BP 		17
#define PIN_OLED_SDA	13
#define PIN_OLED_SCL	12
#define ADC_PINS		2
#define NUM_OF_EFFECTS  3