#define PIN_VOL			23		
#define PIN_FX1			24
#define PIN_NEXT_FX		34
#define PIN_BACK_FX		33
#define PIN_TOGGLE_BP	35
#define PIN_LED_BP 		37
#define PIN_OLED_SDA	13
#define PIN_OLED_SCL	12
#define ADC_PINS		2
#define NUM_OF_EFFECTS  3